version: "3.8"
services:
    flask_backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'python main.py'
        ports:
            - 8001:5000
        volumes:
            - .:/app
        depends_on:
            - db
    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'python consumer.py'
        depends_on:
            - db
    db:
        image: mysql:8
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: main
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - .dbdata:/var/lib/mysql
        ports:
            - 33067:3306
